#!/usr/bin/env node
/** Lossless prose chunk compiler for the authored literary manuscript.
 * Keeps original prose paragraphs and all authored alternatives; does not invent missing episodes.
 */
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'../..');
const inputs=['content/season-1-vertical-slice-episodes-01-02.md',...[3,4,5,6,7,8,9,10].map(e=>`content/season-1-literary-episode-${String(e).padStart(2,'0')}.md`)];
export const sceneOrder={1:[1,2,65,3,4],2:[5,6,7,8,66],3:[9,10,11,12],4:[13,14,15,16],5:[17,18,19,20,21,61],6:[22,23,24,25,58,26],7:[27,59,28,49,29,52,30,55,31,62],8:[32,50,33,53,34,56,35,63],9:[36,37,51,38,54,39,57,40,64,60],10:[41,42,43,44,45,46,47,48]};
const expected=new Set(Object.values(sceneOrder).flat());
const sceneRe=/^#{2,3}\s+(S\d{2})\.\s+(.+)$/;
const headerRe=/^(#{2,6})\s+(.+)$/;
const inlineChoiceRe=/^\*\*Выбор\s+(S\d{2}-C\d+)\s+[^*]*\*\*/;
const metaRe=/^\*\*(?:Место\/время|Участники|Доступ|Доступность|Переменные|Отклик|Состояние|Техническ|Переход|Условие)[^*]*\*\*:?/i;
const skipRe=/^(?:\*\*)?(?:Состояние|Технический переход|Переход|Доступность|Участники|Место\/время|Контракт|Итоговое состояние)(?:\*\*)?\s*:/i;
function chunks(lines){
 const pieces=[];let current={level:0,title:'',paragraphs:[]};let paragraph=[];
 const flush=()=>{if(!paragraph.length)return;let value=paragraph.map(x=>x.trim()).join(' ').trim();paragraph=[];
  if(!value || metaRe.test(value) || skipRe.test(value) || /^\*\*(?:Выбор |Техническ)/.test(value))return;
  current.paragraphs.push(value);
 };
 const store=()=>{flush();if(current.paragraphs.length||current.title)pieces.push({...current,paragraphs:[...current.paragraphs]})};
 for(const line of lines){const h=line.match(headerRe),choice=line.match(inlineChoiceRe);
  if(h){store();current={level:h[1].length,title:h[2].trim(),paragraphs:[]}}
  else if(choice){store();current={level:3,title:`Выбор ${choice[1]}`,paragraphs:[]}}
  else if(!line.trim() || line.startsWith('<!--') || line.startsWith('-->'))flush();
  else paragraph.push(line);
 }
 store();return pieces;
}
export function compileLiterary(){
 const seen=new Map();
 for(const source of inputs){const lines=fs.readFileSync(path.join(root,source),'utf8').split(/\r?\n/);let start=-1,id=null,title='';
  const store=end=>{if(!id)return;const number=Number(id.slice(1));if(seen.has(number))throw Error(`Duplicate scene ${id}`);
   const parts=chunks(lines.slice(start,end));if(!parts.length)throw Error(`Empty scene ${id}`);
   const episode=Number(Object.keys(sceneOrder).find(k=>sceneOrder[k].includes(number)));
   seen.set(number,{id,title,episode,source,chunks:parts});};
  lines.forEach((line,i)=>{const m=line.match(sceneRe);
   if(m){store(i);id=m[1];title=m[2];start=i+1}
   else if(id && /^#{1,3}\s+(?:Техническое состояние|Технические состояния|Технический контракт|Эпизод |Дополнительные)/i.test(line)){
    store(i);id=null;start=-1;
   }
  });store(lines.length);
 }
 const missing=[...expected].filter(x=>!seen.has(x));const extra=[...seen.keys()].filter(x=>!expected.has(x));
 if(missing.length||extra.length)throw Error(`Scene mismatch, missing=${missing}, extra=${extra}`);
 const scenes=Object.values(sceneOrder).flat().map(n=>seen.get(n));
 const c17=scenes.find(x=>x.id==='S17').chunks.find(x=>x.title.startsWith('Выбор S17-C2'));
 if(c17)c17.paragraphs=[];
 for(const scene of scenes){for(const c of scene.chunks){
  c.paragraphs=c.paragraphs.filter(p=>!['- Пойти с Эриком','- Пойти с Ником','- Принять приглашение Дамира','- Оставить время себе','Выбирается ровно одна линия'].some(prefix=>p.startsWith(prefix)));
 }}
 return {schemaVersion:1,edition:'literary-draft-01-10',episodes:10,sceneOrder,scenes};
}
if(process.argv[1] && path.resolve(process.argv[1])===fileURLToPath(import.meta.url)){
 const data=compileLiterary();
 const output=path.join(root,'src/literary-season-data.js');
 fs.writeFileSync(output,'// GENERATED by tools/literary/compile.mjs. Do not edit this file.\nexport const literarySeason = '+JSON.stringify(data)+';\n','utf8');
 console.log('LITERARY_COMPILE_OK',data.scenes.length,'scenes',data.scenes.reduce((n,s)=>n+s.chunks.length,0),'chunks');
}
